RED = "red"
ROY_RED_LOWER = "roy_red_lower"
ROY_RED_UPPER = "roy_red_upper"
ORANGE = "orange"
YELLOW = "yellow"
ROY_YELLOW = "roy_yellow"
GREEN = "green"
ROY_GREEN = "roy_green"
CYAN = "cyan"
BLUE = "blue"
ROY_BLUE = "roy_blue"
INDIGO = "indigo"
VIOLET = "violet"
MAGENTA = "magenta"
WHITE = "white"
BLACK = "black"
roy_colors=[ROY_RED_LOWER, ROY_RED_UPPER, ORANGE, ROY_YELLOW, ROY_GREEN, ROY_BLUE, INDIGO, VIOLET]
rgb_colors=[RED, YELLOW, GREEN, CYAN, BLUE, MAGENTA]
thresholds = {}
red_thresholds = (0,29)
roy_red_lower_thresholds = (0,10)
roy_red_upper_thresholds = (171, 179)
orange_thresholds = (11,20)
yellow_thresholds = (30, 59)
roy_yellow_thresholds = (21,35)
green_thresholds = (60, 89)
roy_green_thresholds = (36,85)
cyan_thresholds = (90, 119)
blue_thresholds = (120, 149)
roy_blue_thresholds = (86,130)
indigo_thresholds = (131,145)
violet_thresholds = (146,170)
magenta_thresholds = (150, 179)

thresholds[RED] = red_thresholds
thresholds[ROY_RED_LOWER] = roy_red_lower_thresholds
thresholds[ROY_RED_UPPER] = roy_red_upper_thresholds
thresholds[ORANGE] = orange_thresholds
thresholds[YELLOW] = yellow_thresholds
thresholds[ROY_YELLOW] = roy_yellow_thresholds
thresholds[GREEN] = green_thresholds
thresholds[ROY_GREEN] = roy_green_thresholds
thresholds[CYAN] = cyan_thresholds
thresholds[BLUE] = blue_thresholds
thresholds[ROY_BLUE] = roy_blue_thresholds
thresholds[INDIGO] = indigo_thresholds
thresholds[VIOLET] = violet_thresholds
thresholds[MAGENTA] = magenta_thresholds